apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  annotations:
    chart2kro.dev/generated: "true"
  labels:
    app.kubernetes.io/managed-by: chart2kro
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 0.1.0
  name: redis
spec:
  resources:
  - id: configmap
    template:
      apiVersion: v1
      data:
        redis.conf: |
          maxmemory-policy allkeys-lru
          appendonly yes
          appendfilename "appendonly.aof"
          save 900 1
          save 300 10
          save 60 10000
      kind: ConfigMap
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        name: release-redis-config
        namespace: default
  - dependsOn:
    - configmap
    id: statefulset
    readyWhen:
    - ${self.status.readyReplicas == self.status.replicas}
    template:
      apiVersion: apps/v1
      kind: StatefulSet
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        name: release-redis
        namespace: default
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/instance: release
            app.kubernetes.io/name: redis
        serviceName: release-redis-headless
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: release
              app.kubernetes.io/name: redis
          spec:
            containers:
            - command:
              - redis-server
              - /etc/redis/redis.conf
              image: ${schema.spec.image.repository}:${schema.spec.image.tag}
              imagePullPolicy: ${schema.spec.image.pullPolicy}
              livenessProbe:
                initialDelaySeconds: 15
                periodSeconds: 10
                tcpSocket:
                  port: redis
              name: redis
              ports:
              - containerPort: 6379
                name: redis
                protocol: TCP
              readinessProbe:
                initialDelaySeconds: 5
                periodSeconds: 5
                tcpSocket:
                  port: redis
              resources:
                limits:
                  cpu: ${schema.spec.resources.limits.cpu}
                  memory: ${schema.spec.resources.limits.memory}
                requests:
                  cpu: ${schema.spec.resources.requests.cpu}
                  memory: ${schema.spec.resources.requests.memory}
              volumeMounts:
              - mountPath: /etc/redis
                name: redis-config
              - mountPath: /data
                name: redis-data
            volumes:
            - configMap:
                name: release-redis-config
              name: redis-config
        volumeClaimTemplates:
        - metadata:
            name: redis-data
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: ${schema.spec.persistence.size}
            storageClassName: ${schema.spec.persistence.storageClass}
  - dependsOn:
    - statefulset
    id: service-headless
    readyWhen:
    - ${self.spec.clusterIP != ""}
    template:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        name: release-redis-headless
        namespace: default
      spec:
        clusterIP: None
        ports:
        - name: redis
          port: ${schema.spec.service.port}
          protocol: TCP
          targetPort: redis
        selector:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        type: ClusterIP
  - dependsOn:
    - statefulset
    id: service-redis
    readyWhen:
    - ${self.spec.clusterIP != ""}
    template:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        name: release-redis
        namespace: default
      spec:
        ports:
        - name: redis
          port: ${schema.spec.service.port}
          protocol: TCP
          targetPort: redis
        selector:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: redis
        type: ${schema.spec.service.type}
  schema:
    apiVersion: redis.redis.kro.run/v1alpha1
    kind: RedisCache
    spec:
      image:
        pullPolicy: string | default="IfNotPresent"
        repository: string | default="redis"
        tag: string | default="7.4-alpine"
      maxmemoryPolicy: string | default="allkeys-lru"
      persistence:
        size: string | default="1Gi"
        storageClass: string
      resources:
        limits:
          cpu: string | default="500m"
          memory: string | default="512Mi"
        requests:
          cpu: string | default="100m"
          memory: string | default="128Mi"
      service:
        port: integer | default=6379
        type: string | default="ClusterIP"
    status:
      service-headlessClusterIP: ${service-headless.spec.clusterIP}
      service-headlessLoadBalancerIP: ${service-headless.status.loadBalancer.?ingress[0].?ip}
      service-redisClusterIP: ${service-redis.spec.clusterIP}
      service-redisLoadBalancerIP: ${service-redis.status.loadBalancer.?ingress[0].?ip}
      statefulsetCurrentReplicas: ${statefulset.status.currentReplicas}
      statefulsetReadyReplicas: ${statefulset.status.readyReplicas}
