apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  annotations:
    chart2kro.dev/generated: "true"
  labels:
    app.kubernetes.io/managed-by: chart2kro
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 0.1.0
  name: nginx
spec:
  resources:
  - id: configmap
    template:
      apiVersion: v1
      data:
        default.conf: |2

          server {
            listen 80;
            server_name _;
            location / {
              root /usr/share/nginx/html;
              index index.html;
            }
            location /health {
              return 200 'ok';
              add_header Content-Type text/plain;
            }
          }
      kind: ConfigMap
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: nginx
        name: release-nginx-config
        namespace: default
  - dependsOn:
    - configmap
    id: deployment
    readyWhen:
    - ${self.status.availableReplicas == self.status.replicas}
    template:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: nginx
        name: release-nginx
        namespace: default
      spec:
        replicas: ${schema.spec.replicaCount}
        selector:
          matchLabels:
            app.kubernetes.io/instance: release
            app.kubernetes.io/name: nginx
        template:
          metadata:
            labels:
              app.kubernetes.io/instance: release
              app.kubernetes.io/name: nginx
          spec:
            containers:
            - image: ${schema.spec.image.repository}:${schema.spec.image.tag}
              imagePullPolicy: ${schema.spec.image.pullPolicy}
              livenessProbe:
                httpGet:
                  path: /health
                  port: http
                initialDelaySeconds: 5
                periodSeconds: 10
              name: nginx
              ports:
              - containerPort: 80
                name: http
                protocol: TCP
              readinessProbe:
                httpGet:
                  path: /health
                  port: http
                initialDelaySeconds: 3
                periodSeconds: 5
              resources:
                limits:
                  cpu: ${schema.spec.resources.limits.cpu}
                  memory: ${schema.spec.resources.limits.memory}
                requests:
                  cpu: ${schema.spec.resources.requests.cpu}
                  memory: ${schema.spec.resources.requests.memory}
              volumeMounts:
              - mountPath: /etc/nginx/conf.d
                name: nginx-config
            volumes:
            - configMap:
                name: release-nginx-config
              name: nginx-config
  - dependsOn:
    - deployment
    id: service
    readyWhen:
    - ${self.spec.clusterIP != ""}
    template:
      apiVersion: v1
      kind: Service
      metadata:
        labels:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: nginx
        name: release-nginx
        namespace: default
      spec:
        ports:
        - name: http
          port: ${schema.spec.service.port}
          protocol: TCP
          targetPort: http
        selector:
          app.kubernetes.io/instance: release
          app.kubernetes.io/name: nginx
        type: ${schema.spec.service.type}
  schema:
    apiVersion: nginx.nginx.kro.run/v1alpha1
    kind: NginxApp
    spec:
      config: string | default="server {\n  listen 80;\n  server_name _;\n  location
        / {\n    root /usr/share/nginx/html;\n    index index.html;\n  }\n  location
        /health {\n    return 200 'ok';\n    add_header Content-Type text/plain;\n  }\n}\n"
      image:
        pullPolicy: string | default="IfNotPresent"
        repository: string | default="nginx"
        tag: string | default="1.27"
      replicaCount: integer | default=1
      resources:
        limits:
          cpu: string | default="250m"
          memory: string | default="256Mi"
        requests:
          cpu: string | default="100m"
          memory: string | default="128Mi"
      service:
        port: integer | default=80
        type: string | default="ClusterIP"
    status:
      deploymentAvailableReplicas: ${deployment.status.availableReplicas}
      deploymentReadyReplicas: ${deployment.status.readyReplicas}
      serviceClusterIP: ${service.spec.clusterIP}
      serviceLoadBalancerIP: ${service.status.loadBalancer.?ingress[0].?ip}
